# Generated by Django 6.1 on 2026-08-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='how_to_apply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
